name: CI - Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Change this to match your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Ensure pytest is installed

    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}"  # Add your project directory to PYTHONPATH

    - name: Print current directory and files
      run: |
        echo "Current working directory: $(pwd)"
        echo "Files in current directory:"
        ls -la

    - name: Print full directory structure
      run: |
        find . -type d -print


    - name: Run tests
      run: |
        python /MSight/run_pytest.py
