name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Upgrade build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine
          python -m pip freeze

      - name: Build the package
        run: python -m build --no-isolation --sdist --wheel --verbose

      - name: Check installed packages
        run: |
          python -m pip freeze
          python -c "import setuptools; print(setuptools.__version__)"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ -z "$(ls -A dist)" ]; then
            echo "Error: No files to upload in dist directory" >&2
            exit 1
          fi
          twine upload dist/* --verbose
